apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: api
data:
  APP_ENV: development
  HTTP_ADDR: ":8081"
  NOTIFIER_ADDR: ":8082"
  OSRM_URL: http://router.project-osrm.org/
  TRIP_SERVICE_ADDR: "trip-service:9093"
  DRIVER_SERVICE_ADDR: "driver-service:9092"
  STRIPE_SUCCESS_URL: "http://localhost:3000?payment=success"
  STRIPE_CANCEL_URL: "http://localhost:3000?payment=cancel"