apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: api
data:
  APP_ENV: development
  HTTP_ADDR: ":8081"
  OSRM_URL: http://router.project-osrm.org/
  TRIP_SERVICE_URL: "trip-service:9093"