apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: ride4Low/notifier:latest
          ports:
            - containerPort: 8082
          env:
            - name: NOTIFIER_ADDR
              value: ":8082"
            - name: DRIVER_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DRIVER_SERVICE_ADDR
---
apiVersion: v1
kind: Service
metadata:
  name: notifier
spec:
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
