apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-credentials
stringData:
  uri: "mongodb://localhost:27017"
  database: "db_name"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "guest"
  password: "abcdedf"
  uri: "amqp://guest:abcdef@rabbitmq:5672/"